name: dartbook_theme_default
description: The 'default' theme resource package for dartbook.
version: 1.0.0
homepage: https://github.com/lindeer/dartbook

environment:
  sdk: '>=2.12.0 <4.0.0'

executables:
  dartbook-theme: main
